apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: relay
resources:
  - namespace.yaml
  - configmap.yaml
  - relay-assistant-deployment.yaml
  - relay-assistant-service.yaml
  - relay-web-deployment.yaml
  - relay-web-service.yaml
  - ingress.yaml
